### ISSUE TITLE
Segmentation fault with large matrices in qp 

### ISSUE THREAD

**Issue by tcchiao** [cvxopt/cvxopt#126]
Hi there, 

I'm getting `Segmentation fault (core dumped)` errors when passing somewhat large matrices to `solvers.qp()`. The P matrix has shape (34638, 34638), and G matrix has shape (138552, 34638) (both sparse matrices). It doesn't seem to be a memory issue since the machine has 100GB of allocated memory and peak memory usage remained at ~30GB before the crash. 

After googling a bit, I tried to reproduce this behavior on my local machine (with considerably less memory) and found that `segmentation fault` appears after the matrices exceeds a certain threshold, while under the threshold I get a `memory error` instead. This is very similar to what's described in https://groups.google.com/forum/#!topic/cvxopt/nxBXtv5WUV4. 
 
```
In [1]: import cvxopt

In [2]: cvxopt.__version__
Out[2]: u'1.2.0'

In [3]: i = 32750

In [4]: G = cvxopt.spmatrix(1,(0,i*4),(0,i))

In [5]: G + 1
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-5-d684893d245a> in <module>()
----> 1 G + 1

MemoryError:

In [6]: i = 32780

In [7]: G = cvxopt.spmatrix(1,(0,i*4),(0,i))

In [8]: G + 1
Segmentation fault: 11
```

The original post mentioned that this is fixed in 1.1.9, and I'm using 1.2.0 here. Any pointers/thoughts on how I should go about debugging this? Thanks a lot in advance for your help!

**Comment by martinandersen** [comment]
Thanks for reporting this! Your example is really helpful—the segmentation fault appears to occur in dense.c:389. I'm not sure yet what the issue is, but we'll look into it.

**Comment by martinandersen** [comment]
The problem is that CXVOPT uses a version of BLAS with 32 bit integers, and this effectively limits the size of arrays. We will most likely fix this issue by throwing an exception if m*n overflows. In principle, you can compile CVXOPT with a BLAS library with 64 bit integers, but this will require some changes. 

You could try a commercial solver like MOSEK, or alternatively, you can see if you can avoid forming a large dense matrix. (For sparse matrices it is only the number of nonzero elements that cannot exceed 2^31-1.)

**Comment by martinandersen** [comment]
Yes, it is true without a fix. The fix will probably be to throw an exception when an attempt is made to create a dense matrix with m*n >= 2^31. In other words, G+1 will still fail if G is sparse and m*n >= 2^31 since it results in a dense matrix.

**Comment by tcchiao** [comment]
Got it, so in my actual code the segmentation fault occurs when I pass G into the solver as `solvers.qp(P, q, G, h)`, where P and G are sparse matrices, q and h are dense matrices. Is there then some operations in `qp` that converts G into a dense matrix? (and could I do something to avoid it?)

**Comment by martinandersen** [comment]
What is the size of G? The KKT solver forms a matrix H = P+G'\*D\*G (where D is a diagonal matrix), so H could become dense even if G is sparse (e.g., if G has a single dense row). Check if P+G'\*G is sparse.

**Comment by tcchiao** [comment]
G matrix has shape (138552, 34638) and is a vertical stack of several matrices. The sub matrices are either diagonal or block diagonal matrices. It is somewhat difficult to get the exact P and G matrix values since the problem is running on a remote machine, so I'm not sure if `P+G'*G` is sparse. 

Changing a solver (or writing less constraints) did both resolve the problem for us though, thanks a lot for your help and suggestions!

**Comment by mirimo1995** [comment]
@tcchiao Hello, I am having the same problem. By changing the solver, did you mean using a different library or changing the solver parameter in cvxopt and if it is the last case, which solver did you use ?
Thank you !

**Comment by martinandersen** [comment]
@mirimo1995, do you have this problem with the latest version of CVXOPT (v1.2.3) or are you using an old version?

**Comment by mirimo1995** [comment]
@martinandersen  Thank you for your quick reply. I am using CVXOPT(v1.2.0).

**Comment by martinandersen** [comment]
The bug referenced in this issue was fixed in v1.2.1—I suggest that you try updating.

**Comment by mirimo1995** [comment]
@martinandersen  Does the last version solves the problem even if the matrix  H = P+G'*D*G  is dense ( nonzero elements exceed 2^31-1) or does it throw an exception ?

**Comment by martinandersen** [comment]
It throws an exception. If there is no way around forming a dense matrix of that size, then you will probably have to look for a different solver. CVXOPT currently uses the "standard" LP64 version of BLAS/LAPACK where integers are 4 bytes. Accommodating the ILP64 version of BLAS/LAPACK will require significant changes. This is something that we would like to do eventually, but it will probably not happen any time soon.

**Comment by mirimo1995** [comment]
Got it. Thanks a lot for your help !

**Comment by AElton363** [comment]
> It throws an exception. If there is no way around forming a dense matrix of that size, then you will probably have to look for a different solver. CVXOPT currently uses the "standard" LP64 version of BLAS/LAPACK where integers are 4 bytes. Accommodating the ILP64 version of BLAS/LAPACK will require significant changes. This is something that we would like to do eventually, but it will probably not happen any time soon.

I would like to solve an unconstrained quadratic optimization problem 1/2 x^T P x + q with dense matrix of size ~10^5 x 10^5. As described, CVXOPT throws an exception ("OverflowError: number of elements exceeds INT_MAX"). 
Can you recommend an alternative solver? 
Thank you and best wishes!

**Comment by ev-br** [comment]
While this is a relatively long-standing issue --- is adding ILP64 build option something you would be willing to consider accepting a patch for? This is going to be a pretty large patch though, which is why I'd rather ask before committing to doing the work.

For reference, we have recently added an option to SciPy (https://github.com/scipy/scipy/pull/22743), so there's some momentum to enable ILP64 across the ecosystem. 

If this is of interest, the way SciPy works is via a build-time option. If enabled, scipy carries both LP64 and ILP64 blas/lapack variants, and individual extensions choose (also at build time) whether they link to an LP64 or to an ILP64 variant. The latter is defined as having a (configurable) suffix, as in `dgemv_64_` etc.

For CVXOPT I'd imagine having both options at runtime is too much, and a build option could be to either use ILP64 variants or to continue doing what it is doing now. 
This way, one could build from source a "controllable world" where NumPy, SciPy and CVXOPT all link to a consistent set of ILP64-enabled LAPACK libraries.
