### ISSUE TITLE
Wheels?

### ISSUE THREAD

**Issue by amueller** [cvxopt/cvxopt#48]
It would be great to have wheels for windows and OS X to ease installation.

**Comment by martinandersen** [comment]
In principle, it would be easy to create a wheel for macOS with a basic version of CVXOPT without any of the optional extensions. However, including the optional extensions adds a dependency on dynamic libraries that are not included with macOS, and hence it is necessary to resort to static linking in order to make a stand-alone wheel.

The situation is worse on Windows since there are no builtin BLAS and LAPACK libraries, so creating a stand-alone wheel must also include (most of) BLAS and LAPACK. There are some efforts to build a static mingw-based toolchain [mingwpy](https://mingwpy.github.io) that makes it possible to build stand-alone wheels for Windows. We are testing this approach via AppVeyor, and here are two links to Windows wheels for Python 2.7 and Python 3.4, in case anyone is interested:

- [CVXOPT 1.1.9 wheel for Python 2.7 (Win64)](https://ci.appveyor.com/api/buildjobs/ayyv7jme1fgm95c9/artifacts/dist/cvxopt-1.1.9%2B4.ga9fa9fc-cp27-cp27m-win_amd64.whl)
- [CVXOPT 1.1.9 wheel for Python 3.4 (Win64)](https://ci.appveyor.com/api/buildjobs/ribp5k7hmt98ew5m/artifacts/dist/cvxopt-1.1.9%2B4.ga9fa9fc-cp34-cp34m-win_amd64.whl)

**Comment by amueller** [comment]
Conda comes with mkl, and you can ship any dynamic library dependencies as separate conda packages - though I imagine most of them exist already.

**Comment by martinandersen** [comment]
CVXOPT can already be installed with conda via the conda-forge channel: https://github.com/conda-forge/cvxopt-feedstock

**Comment by amueller** [comment]
great!

**Comment by martinandersen** [comment]
The [delocate](https://github.com/matthew-brett/delocate) package has made it easy to build self-contained binary extensions for macOS and [PEP 513](https://www.python.org/dev/peps/pep-0513/) and [auditwheel](https://github.com/pypa/auditwheel) has done the same for Linux, so I am reopening this issue. 

We now have a set of cvxopt-1.1.9 wheels for macOS and Linux on the [PyPI testing site](https://testpypi.python.org/pypi/cvxopt/1.1.9) which can be installed as follows:

```
pip install -i https://testpypi.python.org/pypi cvxopt
```

**Comment by martinandersen** [comment]
We now have wheels for Linux, macOS, and Windows.
