### ISSUE TITLE
Interested in travis-ci support for automated testing ?

### ISSUE THREAD

**Issue by cournape** [cvxopt/cvxopt#52]
Hi,

As per #51, we would like to improve cvxopt to support windows natively. As part of the effort, would you be interested in setting up travis-ci (https://travis-ci.com/) and appveyor ? It is free for OSS projects, and has tremendous value for improving quality of contributions, since it automatically tests PRs (most of the packages in the scientific python community uses it)

You would need to allow travis-ci to your repo, but we would be happy to contribute the actual code required to make this work.

**Comment by martinandersen** [comment]
Thank you for the suggestion—I apologize for the incredibly slow response. 

This is something that we have been meaning to set up for some time now, but unfortunately we haven't had the time to do so. I'd be happy to work with you on this. We currently work with two branches, a master branch containing releases and a dev branch where we add minor updates between releases. What is necessary on our end in order to set up travis-ci? 

We currently use the examples for (manually) testing our releases, but it would be very helpful with a more systematic and automated approach to testing.
