### ISSUE TITLE
what is 'y o y'?

### ISSUE THREAD

**Issue by pansmaze** [cvxopt/cvxopt#59]
About misc.ssqr
"""
    The product x := y o y.   The 's' components of y are diagonal and
    only the diagonals of x and y are stored.     
    """
'y o y' = ?
I knew 'matrix a' dot product 'matrix b': a . b
 &  'matrix a' cross product 'matrix b': a * b
but what is y o y...

I searched all over your document, No introduction for lib 'misc' ...

What is x := H(lambda^{1/2}) * x?

**Comment by martinandersen** [comment]
Take a look at the following report that discusses the interior-point algorithms used in the conelp() and coneqp() solvers: [The CVXOPT linear and quadratic cone program solvers](http://www.ee.ucla.edu/~vandenbe/publications/coneprog.pdf) 

The `misc` module is primarily used internally which is why the documentation is limited.
