### ISSUE TITLE
Bound constraints for LP solver when calling GLPK/MOSEK 

### ISSUE THREAD

**Issue by jfowkes** [cvxopt/cvxopt#72]
First of all, I'm a big fan and long-term user of CVXOPT, it provides some great optimization solvers for python in a really neat interface.

However, there is an issue with the current LP solver interface to GLPK/MOSEK: at the moment bound constraints (i.e. of the form `0 <= x_1 <= 1`) have to be explicitly encoded in the coefficient matrix G, and while this is negligible for small problems, it is highly inefficient for large problems since it adds a significant amount of extra constraint equations.

I understand why this is the case for the default `conelp` solver, however both GLPK and MOSEK have dedicated APIs for adding bound constraints and these would be relatively straightforward to incorporate. In light of this, do you think it would be possible to add bound constraints to the `lp` solver when calling GLPK/MOSEK?

**Comment by martinandersen** [comment]
Thank you for your comment and your suggestion. I think that it is a great suggestion, but unfortunately we only have a limited amount of time to spend on CVXOPT, and hence we tend to prioritize developing the CVXOPT solvers rather than the interfaces to external solvers. We primarily see these interfaces as a way to test and validate the CVXOPT solvers rather than as feature-complete interfaces. Moreover, MOSEK provides its own Python module with a more or less complete API. However, as I mentioned, I think it is a great suggestion, and we may add this functionality in the future, if time permits.
